### ISSUE TITLE
Broken since patch 2.06

### ISSUE THREAD

**Issue by Infinimitsu** [ewgf-gg/ewgfgg-frontend#21]
Nothing has updated on any profiles since the latest Tekken 2.06 patch.  Player stats page displays the following: "Unable to fetch stat pentagon; Server busy"

**Comment by the-beef-calculator** [comment]
Hello, I'm aware of the issue, it will be fixed sometime this evening. I've not been able to fix this sooner because I've been out of town for a family emergency. I will update this thread when it is back online. Thanks for using the website :) 


edit: When you say "nothing is updating" are you referring specifically to the stat pentagon, or are your ranked stats also not updating?

**Comment by the-beef-calculator** [comment]
Stat pentagon is fixed, profiles should be updating again. Let me know if you bump into any additional issues!

**Comment by Infinimitsu** [comment]
Stat pentagon is working.  Only thing that I see still not working is the recent opponents list.  Hasn't updated since the patch.

Also, thank you for your hard work on this, and I'm sorry to hear about your family emergency.  Love the website, I use it every session to check on my opponents post sets.
